<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="8" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="SeleniumPracticeTest-Suite" duration-ms="4950" started-at="2019-05-27T09:38:43Z" finished-at="2019-05-27T09:38:48Z">
    <groups>
    </groups>
    <test name="EmpManagementAPITestingUsingRestAssured" duration-ms="4950" started-at="2019-05-27T09:38:43Z" finished-at="2019-05-27T09:38:48Z">
      <class name="com.EmployeManagement.tests.EmployeeManagementTest">
        <test-method status="PASS" signature="deleteEmployeeWithJSONStringTest()[pri:0, instance:com.EmployeManagement.tests.EmployeeManagementTest@5e5792a0]" name="deleteEmployeeWithJSONStringTest" duration-ms="3040" started-at="2019-05-27T09:38:43Z" finished-at="2019-05-27T09:38:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteEmployeeWithJSONStringTest -->
        <test-method status="FAIL" signature="deleteEmployeeWithPayloadTest()[pri:0, instance:com.EmployeManagement.tests.EmployeeManagementTest@5e5792a0]" name="deleteEmployeeWithPayloadTest" duration-ms="1447" started-at="2019-05-27T09:38:46Z" finished-at="2019-05-27T09:38:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [204]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [204]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.EmployeManagement.tests.EmployeeManagementTest.deleteEmployeeWithPayloadTest(EmployeeManagementTest.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteEmployeeWithPayloadTest -->
        <test-method status="PASS" signature="getAllEmployeesTest()[pri:0, instance:com.EmployeManagement.tests.EmployeeManagementTest@5e5792a0]" name="getAllEmployeesTest" duration-ms="57" started-at="2019-05-27T09:38:48Z" finished-at="2019-05-27T09:38:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllEmployeesTest -->
        <test-method status="PASS" signature="getEmployeeTest()[pri:0, instance:com.EmployeManagement.tests.EmployeeManagementTest@5e5792a0]" name="getEmployeeTest" duration-ms="131" started-at="2019-05-27T09:38:48Z" finished-at="2019-05-27T09:38:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEmployeeTest -->
        <test-method status="PASS" signature="postEmployeeWithJSONStringTest()[pri:0, instance:com.EmployeManagement.tests.EmployeeManagementTest@5e5792a0]" name="postEmployeeWithJSONStringTest" duration-ms="61" started-at="2019-05-27T09:38:48Z" finished-at="2019-05-27T09:38:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postEmployeeWithJSONStringTest -->
        <test-method status="FAIL" signature="postEmployeeWithPayloadTest()[pri:0, instance:com.EmployeManagement.tests.EmployeeManagementTest@5e5792a0]" name="postEmployeeWithPayloadTest" duration-ms="38" started-at="2019-05-27T09:38:48Z" finished-at="2019-05-27T09:38:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [204]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [204]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.EmployeManagement.tests.EmployeeManagementTest.postEmployeeWithPayloadTest(EmployeeManagementTest.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postEmployeeWithPayloadTest -->
        <test-method status="PASS" signature="putEmployeeWithJSONStringTest()[pri:0, instance:com.EmployeManagement.tests.EmployeeManagementTest@5e5792a0]" name="putEmployeeWithJSONStringTest" duration-ms="30" started-at="2019-05-27T09:38:48Z" finished-at="2019-05-27T09:38:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- putEmployeeWithJSONStringTest -->
        <test-method status="FAIL" signature="putEmployeeWithPayloadTest()[pri:0, instance:com.EmployeManagement.tests.EmployeeManagementTest@5e5792a0]" name="putEmployeeWithPayloadTest" duration-ms="21" started-at="2019-05-27T09:38:48Z" finished-at="2019-05-27T09:38:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [204]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [204]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.EmployeManagement.tests.EmployeeManagementTest.putEmployeeWithPayloadTest(EmployeeManagementTest.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- putEmployeeWithPayloadTest -->
      </class> <!-- com.EmployeManagement.tests.EmployeeManagementTest -->
    </test> <!-- EmpManagementAPITestingUsingRestAssured -->
  </suite> <!-- SeleniumPracticeTest-Suite -->
</testng-results>
